# Generated by Django 5.0.6 on 2024-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="employee_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="employee_contact",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="employee_department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="employee_desigantion",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="employee_gender",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="employee_joining_date",
            field=models.DateField(null=True),
        ),
    ]
