# Generated by Django 5.0.6 on 2024-06-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employeedetail_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postg_course", models.CharField(max_length=100, null=True)),
                ("postg_passing_year", models.CharField(max_length=30, null=True)),
                ("postg_institiute", models.CharField(max_length=100, null=True)),
                ("postg_percentage", models.CharField(max_length=20, null=True)),
                ("graduation_course", models.CharField(max_length=100, null=True)),
                ("graduation_passing_year", models.CharField(max_length=30, null=True)),
                ("graduation_institiute", models.CharField(max_length=100, null=True)),
                ("graduation_percentage", models.CharField(max_length=20, null=True)),
                ("highers_course", models.CharField(max_length=100, null=True)),
                ("highers_passing_year", models.CharField(max_length=30, null=True)),
                ("highers_institiute", models.CharField(max_length=100, null=True)),
                ("highers_percentage", models.CharField(max_length=20, null=True)),
                ("scondary_course", models.CharField(max_length=100, null=True)),
                ("scondary_passing_year", models.CharField(max_length=30, null=True)),
                ("scondary_institiute", models.CharField(max_length=100, null=True)),
                ("scondary_percentage", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compnay1_name", models.CharField(max_length=100, null=True)),
                ("company1_desigantion", models.CharField(max_length=100, null=True)),
                ("company1_duration", models.CharField(max_length=100, null=True)),
                ("company1_salary", models.CharField(max_length=100, null=True)),
                ("compnay2_name", models.CharField(max_length=100, null=True)),
                ("company2_desigantion", models.CharField(max_length=100, null=True)),
                ("company2_duration", models.CharField(max_length=100, null=True)),
                ("company2_salary", models.CharField(max_length=100, null=True)),
                ("compnay3_name", models.CharField(max_length=100, null=True)),
                ("company3_desigantion", models.CharField(max_length=100, null=True)),
                ("company3_duration", models.CharField(max_length=100, null=True)),
                ("company3_salary", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
